name: Install Volatility3 test
on: [push, pull_request]
jobs:

  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Setup python-pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install volatility3
      run: pip install .

    - name: Run volatility3
      run: vol --help